import type { Metadata } from 'next';
import {
  TrendingDown,
  Receipt,
  Leaf,
  Building2,
  Zap,
  IndianRupee,
  CheckCircle,
  MapPin,
} from 'lucide-react';
import SectionWrapper from '@/components/SectionWrapper';
import SectionHeading from '@/components/SectionHeading';
import CTAButton from '@/components/CTAButton';

export const metadata: Metadata = {
  title: 'Commercial Solar Installation',
  description:
    'Scalable rooftop solar solutions for offices, factories, and housing societies in Delhi-NCR. Reduce electricity costs, earn GBI, and get accelerated depreciation benefits.',
};

const benefits = [
  {
    icon: TrendingDown,
    title: 'Reduce Electricity Costs',
    description: 'Cut your electricity bill by 50-90% with rooftop solar. The larger your consumption, the greater your savings.',
  },
  {
    icon: Receipt,
    title: 'Accelerated Depreciation',
    description: '40% accelerated depreciation benefit available for commercial solar installations, significantly reducing your tax liability.',
  },
  {
    icon: IndianRupee,
    title: 'Generation-Based Incentive',
    description: 'Earn Rs 2/kWh from the Delhi government for 5 years on all solar power generated by your system.',
  },
  {
    icon: Leaf,
    title: 'Green Credentials',
    description: 'Demonstrate your commitment to sustainability. Reduce your carbon footprint and enhance your brand image.',
  },
];

const segments = [
  'Office buildings',
  'Factories and manufacturing units',
  'Warehouses',
  'Housing societies (group net metering)',
  'Schools and educational institutions',
  'Hospitals and clinics',
  'Hotels and restaurants',
  'Retail stores and malls',
];

const serviceAreas = [
  { area: 'Delhi', note: 'GBI + Net metering via BSES' },
  { area: 'Faridabad', note: 'Net metering available' },
  { area: 'Gurgaon', note: 'Net metering available' },
];

export default function CommercialSolarPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'Service',
            name: 'Commercial Solar Installation',
            provider: { '@type': 'Organization', name: 'Raytrix Energy (OPC) Private Limited' },
            areaServed: ['Delhi', 'Faridabad', 'Gurgaon'],
            serviceType: 'Commercial Solar Panel Installation',
          }),
        }}
      />

      <section className="bg-primary py-12 sm:py-16">
        <div className="mx-auto max-w-7xl px-4 text-center sm:px-6 lg:px-8">
          <h1 className="font-heading text-3xl font-bold text-text-inverse sm:text-4xl">
            Commercial Solar Installation
          </h1>
          <p className="mx-auto mt-3 max-w-2xl text-base text-gray-300 sm:text-lg">
            Scalable rooftop solar for businesses. Reduce costs, earn incentives, go green.
          </p>
        </div>
      </section>

      {/* Benefits */}
      <SectionWrapper>
        <SectionHeading
          title="Why Commercial Solar?"
          subtitle="Solar is not just green — it's smart business."
        />
        <div className="grid gap-6 md:grid-cols-2">
          {benefits.map((b) => (
            <div key={b.title} className="rounded-2xl bg-bg-white p-6 shadow-md">
              <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10">
                <b.icon className="h-6 w-6 text-primary" />
              </div>
              <h3 className="font-heading text-lg font-bold text-text">{b.title}</h3>
              <p className="mt-2 text-sm leading-relaxed text-text-light">{b.description}</p>
            </div>
          ))}
        </div>
      </SectionWrapper>

      {/* System Sizes */}
      <SectionWrapper className="bg-bg-white">
        <SectionHeading
          title="System Sizes"
          subtitle="From small offices to large factories — we scale to your needs."
        />
        <div className="mx-auto max-w-3xl">
          <div className="grid gap-4 sm:grid-cols-3">
            {[
              { range: '1 - 10 KW', label: 'Small Office', icon: Building2 },
              { range: '10 - 50 KW', label: 'Medium Business', icon: Building2 },
              { range: '50+ KW', label: 'Large Commercial', icon: Building2 },
            ].map((size) => (
              <div key={size.range} className="rounded-2xl bg-bg p-5 text-center">
                <size.icon className="mx-auto h-8 w-8 text-primary" />
                <p className="mt-3 font-heading text-xl font-bold text-text">{size.range}</p>
                <p className="text-sm text-text-light">{size.label}</p>
              </div>
            ))}
          </div>
          <p className="mt-4 text-center text-sm text-text-light">
            No upper limit on system size. We design and install systems tailored to your roof space and energy consumption.
          </p>
        </div>
      </SectionWrapper>

      {/* Segments */}
      <SectionWrapper>
        <SectionHeading
          title="Industries We Serve"
          subtitle="Solar works for every type of commercial establishment."
        />
        <div className="mx-auto max-w-2xl">
          <div className="grid gap-3 sm:grid-cols-2">
            {segments.map((seg) => (
              <div key={seg} className="flex items-center gap-3 rounded-xl bg-bg-white p-4 shadow-sm">
                <CheckCircle className="h-5 w-5 flex-shrink-0 text-accent" />
                <span className="text-sm text-text">{seg}</span>
              </div>
            ))}
          </div>
        </div>
      </SectionWrapper>

      {/* Net Metering & GBI */}
      <SectionWrapper className="bg-bg-white">
        <SectionHeading title="Net Metering & Incentives" />
        <div className="mx-auto max-w-3xl">
          <div className="grid gap-6 md:grid-cols-2">
            <div className="rounded-2xl bg-bg p-6">
              <Zap className="h-8 w-8 text-secondary" />
              <h3 className="mt-3 font-heading text-lg font-bold text-text">Net Metering</h3>
              <p className="mt-2 text-sm text-text-light">
                Export excess solar power to the grid and get it adjusted against your electricity bill.
                Your meter runs backwards when you generate more than you consume.
              </p>
            </div>
            <div className="rounded-2xl bg-bg p-6">
              <IndianRupee className="h-8 w-8 text-accent" />
              <h3 className="mt-3 font-heading text-lg font-bold text-text">Generation-Based Incentive</h3>
              <p className="mt-2 text-sm text-text-light">
                Delhi government pays Rs 2/kWh for commercial systems (3-10 KW) for 5 years.
                This is on top of your electricity savings — directly credited to your account.
              </p>
            </div>
          </div>
        </div>
      </SectionWrapper>

      {/* Financing */}
      <SectionWrapper>
        <div className="mx-auto max-w-3xl rounded-2xl bg-primary/5 p-6 text-center sm:p-8">
          <IndianRupee className="mx-auto h-10 w-10 text-primary" />
          <h2 className="mt-3 font-heading text-xl font-bold text-text sm:text-2xl">
            Financing & Loan Assistance
          </h2>
          <p className="mt-2 text-sm text-text-light sm:text-base">
            We help commercial customers apply for solar loans, making it possible to go solar
            with minimal upfront investment. The system pays for itself through electricity savings.
          </p>
        </div>
      </SectionWrapper>

      {/* Service Areas */}
      <SectionWrapper className="bg-bg-white">
        <SectionHeading title="Service Areas" />
        <div className="mx-auto max-w-2xl space-y-3">
          {serviceAreas.map((sa) => (
            <div key={sa.area} className="flex items-center justify-between rounded-xl bg-bg p-4">
              <div className="flex items-center gap-3">
                <MapPin className="h-5 w-5 text-primary" />
                <span className="font-heading font-bold text-text">{sa.area}</span>
              </div>
              <span className="text-sm text-text-light">{sa.note}</span>
            </div>
          ))}
        </div>
      </SectionWrapper>

      {/* CTA */}
      <SectionWrapper>
        <div className="text-center">
          <h2 className="font-heading text-2xl font-bold text-text sm:text-3xl">
            Get a Custom Assessment
          </h2>
          <p className="mt-2 text-text-light">
            Every commercial project is unique. Contact us for a free site survey and tailored quote.
          </p>
          <div className="mt-6">
            <CTAButton text="Contact Us for Assessment" href="/contact" />
          </div>
        </div>
      </SectionWrapper>
    </>
  );
}
